version: '0.2'
language: en
ignorePaths:
    - node_modules
    - dist
    - build
    - .git

dictionaryDefinitions:
    - name: custom-words
      path: ./cspell/custom-words.txt
      addWords: true

dictionaries:
    - custom-words
